### PR TITLE
OZ-523: Setup Ozone E2E versioning

### PR DESCRIPTION
**Pull request by kdaud**
Ticket [OZ-523](https://mekomsolutions.atlassian.net/browse/OZ-523)

This PR sets the Ozone E2E version being published on NPM Registry.

[OZ-523]: https://mekomsolutions.atlassian.net/browse/OZ-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vasharma05** [comment]
Are we not using the Ozone version?

**Comment by kdaud** [comment]
> Are we not using the Ozone version?

Sure, we're to use Ozone versioning.

**Comment by vasharma05** [comment]
You didn't add the `ozVersion` in the package.json, nor in the CI job

**Comment by kdaud** [comment]
> You didn't add the ozVersion in the package.json, nor in the CI job

I believe we don't need to include the `ozVersion`. The Ozone E2E test packages should be linked to the tested Ozone version.

**Review by vasharma05 — APPROVED** [review]
Thanks @kdaud !

**Comment by kdaud** [comment]
@vasharma05 the push job is working as expected.

**Pull request merged**
